### ISSUE TITLE
Trouble with Calgary transit. 

### ISSUE THREAD

**Issue by SmAsH-jl** [mark1foley/ha-gtfs-rt-v2#10]
I can't get seem to get it to work with this data set. 

```
trip_update_url: 'https://data.calgary.ca/api/views/gs4m-mdc2/files/be59ec25-b97a-46ca-9297-4591fc0c2816?filename=tripupdates.pb'
vehicle_position_url: 'https://data.calgary.ca/api/views/am7c-qe3u/files/90adc2ee-dd09-4efd-90af-7c38d89466c9?filename=vehiclepositions.pb'
route_delimiter: '-'
departures:
- name: "test stop"
  route: '3'
  stopid: '6662'
```

It always returns - as the output. anyone help?

```
DEBUG:__main__:...Feed Route Id 3 changed to 3
DEBUG:__main__:......Stop: 6662 Stop Sequence: 1 Stop Time: 1674686100
DEBUG:__main__:......Stop: 5154 Stop Sequence: 2 Stop Time: 1674686170
DEBUG:__main__:......Stop: 8746 Stop Sequence: 3 Stop Time: 1674686234
DEBUG:__main__:......Stop: 5155 Stop Sequence: 4 Stop Time: 1674686293
DEBUG:__main__:......Stop: 8747 Stop Sequence: 5 Stop Time: 1674686347
DEBUG:__main__:......Stop: 5156 Stop Sequence: 6 Stop Time: 1674686409
DEBUG:__main__:......Stop: 7535 Stop Sequence: 7 Stop Time: 1674686474
DEBUG:__main__:......Stop: 7536 Stop Sequence: 8 Stop Time: 1674686540
DEBUG:__main__:......Stop: 7537 Stop Sequence: 9 Stop Time: 1674686600
DEBUG:__main__:......Stop: 5157 Stop Sequence: 10 Stop Time: 1674686647
DEBUG:__main__:......Stop: 5579 Stop Sequence: 11 Stop Time: 1674686700
DEBUG:__main__:......Stop: 5806 Stop Sequence: 12 Stop Time: 1674686756
DEBUG:__main__:......Stop: 5159 Stop Sequence: 13 Stop Time: 1674686847
DEBUG:__main__:......Stop: 8619 Stop Sequence: 14 Stop Time: 1674686895
DEBUG:__main__:......Stop: 8620 Stop Sequence: 15 Stop Time: 1674686948
DEBUG:__main__:......Stop: 8621 Stop Sequence: 16 Stop Time: 1674687002
DEBUG:__main__:......Stop: 5160 Stop Sequence: 17 Stop Time: 1674687060
INFO:__main__:Sensor Update:
INFO:__main__:...Name: 16W Ave N WB
INFO:__main__:...Route: 3
INFO:__main__:...Stop ID: 6662
INFO:__main__:...Direction ID: 0
INFO:__main__:...Icon: mdi:bus
INFO:__main__:...Service Type: Service
INFO:__main__:...unit_of_measurement: min
INFO:__main__:...Due in: -
INFO:__main__:...Due at not defined
INFO:__main__:...Latitude not defined
INFO:__main__:...Longitude not defined
INFO:__main__:...Next Service not defined
```

**Comment by mark1foley** [comment]
Hi, the data that is being published by Calgary Transit looks strangle.  However, I saw a notice on their website today saying that "Our real-time service is currently unavailable on our website and applications.  We are working to fix the issue, thank you for your patience.".  I might wait until they have resolved this issue before looking at it any further.

Regards,

Mark

**Comment by SmAsH-jl** [comment]
> I saw a notice on their website today saying that "Our real-time service is currently unavailable on our website and applications. We are working to fix the issue, thank you for your patience.". I might wait until they have resolved this issue before looking at it any further.

I'm sorry Mark you  where right. It started working again after the outage. I missed the Service status updates. 

Working great today.

**Comment by mark1foley** [comment]
Hi,

Thanks for letting me know.  By the way, were did you get the URLs above from?  From what I can see the ones on the Calgary Transit open data site are different, and seem to work a bit better.  There are:
trip_update_url: 'https://data.calgary.ca/download/gs4m-mdc2/application%2Foctet-stream'
vehicle_position_url: 'https://data.calgary.ca/download/am7c-qe3u/application%2Foctet-stream'

**Comment by SmAsH-jl** [comment]
Yea. I ended up finding those versions later and am now using the proper
set. I had copied them from the "download link" in the chrome tab.  so a
weird cached version?
