### ISSUE TITLE
gtfs_rt implements device_state_attributes.

### ISSUE THREAD

**Issue by grehund** [mark1foley/ha-gtfs-rt-v2#2]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:583
First occurred: 3:46:35 PM (3 occurrences)
Last logged: 3:46:35 PM

Entity sensor.ferny_grove_train (<class 'custom_components.gtfs_rt.sensor.PublicTransportSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.uni_qld_ferry (<class 'custom_components.gtfs_rt.sensor.PublicTransportSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.1_0_7_bus (<class 'custom_components.gtfs_rt.sensor.PublicTransportSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by mark1foley** [comment]
Hi, this has been fixed in release 1.20220316.01 onwards
