### ISSUE TITLE
How do you pass custom headers to URL calls?

### ISSUE THREAD

**Issue by rafaelmagu** [mark1foley/ha-gtfs-rt-v2#27]
Seeing as https://github.com/zacs/ha-gtfs-rt now has support for custom headers, it solved a major blocker I had with connecting to Auckland Transport's API, which requires a header named `Ocp-Apim-Subscription-Key` with the actual API key for my account. I also need to send `Accept: application/x-protobuf` alongside the token to ensure the API returns the correct data format.

What support is there in this version to pass custom headers?

**Comment by mark1foley** [comment]
Latest release has support for custom headers
