### ISSUE TITLE
Error get_gtfs_feed_entities

### ISSUE THREAD

**Issue by jllarraz** [mark1foley/ha-gtfs-rt-v2#28]
This is the error from the console

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: 15:05:38 (1 occurrences)
Last logged: 15:05:38

Error while setting up gtfs_rt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gtfs_rt/sensor.py", line 108, in setup_platform
    PublicTransportSensor(
  File "/config/custom_components/gtfs_rt/sensor.py", line 155, in __init__
    self.update()
  File "/config/custom_components/gtfs_rt/sensor.py", line 221, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gtfs_rt/sensor.py", line 297, in update
    self._get_vehicle_positions()
  File "/config/custom_components/gtfs_rt/sensor.py", line 429, in _get_vehicle_positions
    feed_entities = get_gtfs_feed_entities(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gtfs_rt/sensor.py", line 139, in get_gtfs_feed_entities
    feed.ParseFromString(response.content)
google.protobuf.message.DecodeError: Error parsing message
`

And this is my configuration of the sensor
`- platform: gtfs_rt
  trip_update_url: 'https://api.nationaltransport.ie/gtfsr/v2/TripUpdates?format=json'
  vehicle_position_url: 'https://api.nationaltransport.ie/gtfsr/v2/Vehicles?format=json'
  x_api_key: 'REDACTED'
  departures:
    - name: 120 from Ashtown To Parnell Street
      route: "3762_58545"
      stopid: "8220DB007028"
      icon: mdi:bus
      service_type: "Bus"`

And this is the url of the provider in case its useful [https://developer.nationaltransport.ie/api-details#api=gtfsr&operation=gtfsr-v2](url)

[Trips_Updates_Response.txt](https://github.com/mark1foley/ha-gtfs-rt-v2/files/13705482/Trips_Updates_Response.txt)
[Vehicles_Response.txt](https://github.com/mark1foley/ha-gtfs-rt-v2/files/13705490/Vehicles_Response.txt)

**Comment by mark1foley** [comment]
Please remove the ?format=json text from the URLs

**Comment by jllarraz** [comment]
Thanks that worked but unfortunately the sensor is coming back always as "dueIn":"-". After looking into it, it turns out that The Irish National Transport is providing a file with the static schedules against I should be checking the info provided by those Endpoints. I did find another project for that dataset where they explain in detail the issue [https://github.com/Jerry-F-1/GTFS-Irl-V2-Home-Assistant](url). It will be great if your project adds the option to add a static file with the schedules or a url option to pull them down every x time (To update them, the Irish Transport Authority is planning to provide that via API). Nevertheless is an impressive project and thanks for your support.
