### ISSUE TITLE
YAML Configuration Issue: Sequence entries not valid here

### ISSUE THREAD

**Issue by staticlama** [mark1foley/ha-gtfs-rt-v2#4]
Hello,

Thank you for the work on a translink compatible realtime feed. I've installed the integration using HACS but HA has an issue with this line in the config:

`    route_delimiter: -`

I've tried a few different versions e.g. 
`    route_delimiter: '-'` and
`    route_delimiter: "-"`

Using quotes allows the configuration file to pass validation but no departure times show up in the sensors. 

The error message I receive is:
`The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: sequence entries are not allowed here in "/config/configuration.yaml", line 39, column 22
`

Home assistant version info:

- Home Assistant Core 2022.6.7
- Home Assistant Supervisor 2022.05.3
- Home Assistant OS 8.2

Any help would be appreciated! Thank you

**Comment by samsquanch2000** [comment]
Having the same issue here.
