### ISSUE TITLE
Montreal Metro

### ISSUE THREAD

**Issue by nips1900** [mark1foley/ha-gtfs-rt-v2#6]
Hi,

i'm using your application for Montreal Bus & Metro. For buses it is working perfetly, but i have hard time with metro. I can't get any information.

please find my config below:

sensor:

platform: gtfs_rt
trip_update_url: 'https://api.stm.info/pub/od/gtfs-rt/ic/v2/tripUpdates'
vehicle_position_url: 'https://api.stm.info/pub/od/gtfs-rt/ic/v2/vehiclePositions'
apikey: 'l7xx12345678912346764564564'
departures:
name: 'Bus 178'
route: 168
stopid: 56698

name: 'STM Ligne Verte'
route: 1
stopid: 36

could you please let me know what i'm doing wrong?

thank you,

Laurent

**Comment by mark1foley** [comment]
Hi,

Apologies for the delayed response but I have been on holidays.  Looking at the configuration you supplied the API key variable is 'api_key' and not 'apikey'.  Please update the variable name and let me know how you go.

Regards,
Mark
